development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= "http://#{ENV['HYDRASTAGINGJETTY_PORT_8983_TCP_ADDR']}:8983/fedora3" %>
test: &TEST  
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= "http://127.0.0.1:#{ENV['TEST_JETTY_PORT'] || 8983}/fedora-test" %>
production:
  user: fedoraAdmin
  password: root
  url: <%= "http://#{ENV['HYDRAPRODUCTIONJETTY_PORT_8983_TCP_ADDR']}:8983/fedora3" %>
cucumber:
  <<: *TEST
