development:
  user: fedoraAdmin
  password: root
  url: http://fcommons-dev.osfashland.org:8080/fedora
test: &TEST  
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= "http://127.0.0.1:#{ENV['TEST_JETTY_PORT'] || 8983}/fedora-test" %>
production:
  user: fedoraAdmin
  password: root
  url: http://fcommons-dev.osfashland.org:8080/fedora
cucumber:
  <<: *TEST
